name: tests

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.0', 8.1, 8.2, 8.3]
        laravel: [^9.0, ^10.0, ^11.0]
        exclude:
          - php: '8.0'
            laravel: ^10.0
          - php: '8.0'
            laravel: ^11.0
          - php: 8.1
            laravel: ^11.0

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit
